#!/usr/bin/env python

# Generated by mock-builder

from flask import Flask, request

app = Flask(__name__)

@app.route("/v2.0/tokens", methods=["POST"])
def post_v2_0_tokens():
    return ('''{"access": {"token": {"expires": "2013-10-27T17:35:30Z", "id": "00000000000000000000000000000000", "tenant": {"description": null, "enabled": true, "id": "cf3bb63b1e8540dbbbce1902af2ff1f6", "name": "mgreenway"}}, "serviceCatalog": [{"endpoints": [{"adminURL": "http://127.0.0.1:8776/v1/cf3bb63b1e8540dbbbce1902af2ff1f6", "region": "RegionOne", "publicURL": "http://127.0.0.1:8776/v1/cf3bb63b1e8540dbbbce1902af2ff1f6", "internalURL": "http://127.0.0.1:8776/v1/cf3bb63b1e8540dbbbce1902af2ff1f6"}], "endpoints_links": [], "type": "volume", "name": "Volume Service"}, {"endpoints": [{"adminURL": "http://127.0.0.1:9292/v1", "region": "RegionOne", "publicURL": "http://127.0.0.1:9292/v1", "internalURL": "http://127.0.0.1:9292/v1"}], "endpoints_links": [], "type": "image", "name": "Image Service"}, {"endpoints": [{"adminURL": "http://127.0.0.1:8774/v1.1/cf3bb63b1e8540dbbbce1902af2ff1f6", "region": "RegionOne", "publicURL": "http://127.0.0.1:8774/v1.1/cf3bb63b1e8540dbbbce1902af2ff1f6", "internalURL": "http://127.0.0.1:8774/v1.1/cf3bb63b1e8540dbbbce1902af2ff1f6"}], "endpoints_links": [], "type": "compute", "name": "Compute Service"}, {"endpoints": [{"adminURL": "http://127.0.0.1:8773/services/Admin", "region": "RegionOne", "publicURL": "http://127.0.0.1:8773/services/Cloud", "internalURL": "http://127.0.0.1:8773/services/Cloud"}], "endpoints_links": [], "type": "ec2", "name": "EC2 Service"}, {"endpoints": [{"adminURL": "http://127.0.0.1:35357/v2.0", "region": "RegionOne", "publicURL": "http://127.0.0.1:5000/v2.0", "internalURL": "http://127.0.0.1:5000/v2.0"}], "endpoints_links": [], "type": "identity", "name": "Identity Service"}], "user": {"username": "mgreenway", "roles_links": [], "id": "6a84f76927bb450d84f3369db7442a08", "roles": [{"id": "7cc444dd12f4413c90f1f19e3c109f99", "name": "Member"}], "name": "mgreenway"}}}''', 200, {'Content-Type': 'application/json', 'Vary': 'X-Auth-Token', 'Date': 'Sat, 26 Oct 2013 17:35:30 GMT', })

if __name__ == "__main__": app.run(host="127.1", debug=True, port=5000)
